
MODULE_TOPDIR = ../..

SUBDIRS = \
	r.avaflow \
	r.avaflow.main \
	r.avaflow.mult \
	r.avaflow.paraview \
	r.avaflow.background \
	r.lakefill

include $(MODULE_TOPDIR)/include/Make/Dir.make

default: parsubdirs
install: installsubdirs
